#!/usr/bin/env python3
# 生成 dcn314_truth.txt：从 Linux dcn_3_1_4_offset.h / _sh_mask.h 提取
# DCN314.hpp 全部常量的权威值（键 = 项目常量名，值 = 十六进制）。
# 逐字节核对：每个条目都给出头文件里的宏名，test_dcn314_regs.cpp 以此比对。
#
# 用法：python3 src/NootedRed/Regs/tests/mk_check.py > build/dcn314_truth.txt

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[4]
REF = ROOT / "oldfiles-handoff/reference/linux/drivers/gpu/drm/amd/include/asic_reg/dcn"
OFF = (REF / "dcn_3_1_4_offset.h").read_text()
MASK = (REF / "dcn_3_1_4_sh_mask.h").read_text()
SEG = (ROOT / "oldfiles-handoff/reference/linux/drivers/gpu/drm/amd/include/yellow_carp_offset.h").read_text()


def offval(macro: str) -> int:
    m = re.search(rf"^#define {macro}\s+(0x[0-9a-fA-F]+)", OFF, re.M)
    assert m, f"offset 头文件中找不到 {macro}"
    return int(m.group(1), 16)


def maskval(block: str, field: str) -> int:
    m = re.search(rf"^#define {block}__{field}_MASK\s+(0x[0-9a-fA-F]+)", MASK, re.M)
    assert m, f"sh_mask 头文件中找不到 {block}__{field}_MASK"
    return int(m.group(1), 16)


def shiftval(block: str, field: str) -> int:
    m = re.search(rf"^#define {block}__{field}__SHIFT\s+(0x[0-9a-fA-F]+)", MASK, re.M)
    assert m, f"sh_mask 头文件中找不到 {block}__{field}__SHIFT"
    return int(m.group(1), 16)


def segval(macro: str) -> int:
    m = re.search(rf"^#define {macro}\s+(0x[0-9a-fA-F]+)", SEG, re.M)
    assert m, f"yellow_carp_offset.h 中找不到 {macro}"
    return int(m.group(1), 16)


# 项目常量名 → (Linux 头文件宏, 来源文件)
# offset 类：dcn_3_1_4_offset.h 的 regXXX / regXXX_BASE_IDX
# mask 类：dcn_3_1_4_sh_mask.h 的 XXX__YYY_MASK
ENTRIES = {
    # ── DCCG（时钟门控/分频，时钟主流程）──
    "DCCG_GATE_DISABLE_CNTL": "regDCCG_GATE_DISABLE_CNTL",
    "DCCG_GATE_DISABLE_CNTL2": "regDCCG_GATE_DISABLE_CNTL2",
    "DCCG_GATE_DISABLE_CNTL3": "regDCCG_GATE_DISABLE_CNTL3",
    "DCCG_DISP_CNTL_REG": "regDCCG_DISP_CNTL_REG",
    "OTG_PIXEL_RATE_DIV": "regOTG_PIXEL_RATE_DIV",
    "DIG1_DIG_FE_CNTL": "regDIG1_DIG_FE_CNTL",
    "DPPCLK_DTO_CTRL": "regDPPCLK_DTO_CTRL",
    "DPPCLK0_DTO_PARAM": "regDPPCLK0_DTO_PARAM",
    "DTBCLK_P_CNTL": "regDTBCLK_P_CNTL",
    "DIG4_DIG_FE_CNTL": "regDIG4_DIG_FE_CNTL",
    # ── 既有常量回归（改前 76 条全量）──
    "HUBPRET_CONTROL": "regHUBPRET0_HUBPRET_CONTROL",
    "HUBP_SURFACE_CONFIG": "regHUBP0_DCSURF_SURFACE_CONFIG",
    "HUBP_ADDR_CONFIG": "regHUBP0_DCSURF_ADDR_CONFIG",
    "HUBP_TILING_CONFIG": "regHUBP0_DCSURF_TILING_CONFIG",
    "HUBP_PRI_VIEWPORT_START": "regHUBP0_DCSURF_PRI_VIEWPORT_START",
    "HUBP_PRI_VIEWPORT_DIMENSION": "regHUBP0_DCSURF_PRI_VIEWPORT_DIMENSION",
    "HUBPREQ_SURFACE_PITCH": "regHUBPREQ0_DCSURF_SURFACE_PITCH",
    "HUBPREQ_PRIMARY_SURFACE_ADDRESS": "regHUBPREQ0_DCSURF_PRIMARY_SURFACE_ADDRESS",
    "HUBPREQ_PRIMARY_SURFACE_ADDRESS_HIGH": "regHUBPREQ0_DCSURF_PRIMARY_SURFACE_ADDRESS_HIGH",
    "HUBPREQ_FLIP_CONTROL": "regHUBPREQ0_DCSURF_FLIP_CONTROL",
    "HUBPREQ_SURFACE_EARLIEST_INUSE": "regHUBPREQ0_DCSURF_SURFACE_EARLIEST_INUSE",
    "HUBPREQ_SURFACE_EARLIEST_INUSE_HIGH": "regHUBPREQ0_DCSURF_SURFACE_EARLIEST_INUSE_HIGH",
    "OTG_CONTROL": "regOTG0_OTG_CONTROL",
    "OTG_INTERLACE_CONTROL": "regOTG0_OTG_INTERLACE_CONTROL",
    "OPTC_WIDTH_CONTROL": "regODM0_OPTC_WIDTH_CONTROL",
    "OPTC_MEMORY_CONFIG": "regODM0_OPTC_MEMORY_CONFIG",
    "OPPBUF_3D_PARAMETERS_0": "regOPPBUF0_OPPBUF_3D_PARAMETERS_0",
    "OPP_PIPE_CONTROL": "regOPP_PIPE0_OPP_PIPE_CONTROL",
    "OPP_TOP_CLK_CONTROL": "regOPP_TOP_CLK_CONTROL",
    "MPCC_TOP_SEL": "regMPCC0_MPCC_TOP_SEL",
    "MPC_OUT0_MUX": "regMPC_OUT0_MUX",
    "MICROSECOND_TIME_BASE_DIV": "regMICROSECOND_TIME_BASE_DIV",
    "DC_MEM_GLOBAL_PWR_REQ_CNTL": "regDC_MEM_GLOBAL_PWR_REQ_CNTL",
    "DENTIST_DISPCLK_CNTL": "regDENTIST_DISPCLK_CNTL",
    "DISPCLK_FREQ_CHANGE_CNTL": "regDISPCLK_FREQ_CHANGE_CNTL",
    "SYMCLK32_SE_CNTL": "regSYMCLK32_SE_CNTL",
    "OTG_PIXEL_RATE_CNTL": "regOTG0_PIXEL_RATE_CNTL",
    "OTG1_PIXEL_RATE_CNTL": "regOTG1_PIXEL_RATE_CNTL",
    "OTG2_PIXEL_RATE_CNTL": "regOTG2_PIXEL_RATE_CNTL",
    "OTG3_PIXEL_RATE_CNTL": "regOTG3_PIXEL_RATE_CNTL",
    "DP_DTO_PHASE": "regDP_DTO0_PHASE",
    "PHYPLLA_PIXCLK_RESYNC_CNTL": "regPHYPLLA_PIXCLK_RESYNC_CNTL",
    "DIG_FE_CNTL": "regDIG0_DIG_FE_CNTL",
    "DIG_AFMT_CNTL": "regDIG0_AFMT_CNTL",
    "DIG_BE_CNTL": "regDIG0_DIG_BE_CNTL",
    "DIG_BE_EN_CNTL": "regDIG0_DIG_BE_EN_CNTL",
    "OTG_H_TIMING_CNTL": "regOTG0_OTG_H_TIMING_CNTL",
    "OPTC_DATA_SOURCE_SELECT": "regODM0_OPTC_DATA_SOURCE_SELECT",
    "MPCC_UPDATE_LOCK_SEL": "regMPCC0_MPCC_UPDATE_LOCK_SEL",
    "DIG_CLOCK_PATTERN": "regDIG0_DIG_CLOCK_PATTERN",
    "DIG_FIFO_CTRL0": "regDIG0_DIG_FIFO_CTRL0",
    # ── DP/流编码器（STE 基础集）──
    "DP_PIXEL_FORMAT": "regDP0_DP_PIXEL_FORMAT",
    "DP_CONFIG": "regDP0_DP_CONFIG",
    "DP_VID_STREAM_CNTL": "regDP0_DP_VID_STREAM_CNTL",
    "DP_STEER_FIFO": "regDP0_DP_STEER_FIFO",
    "DP_MSA_MISC": "regDP0_DP_MSA_MISC",
    "DP_VID_TIMING": "regDP0_DP_VID_TIMING",
    "DP_VID_N": "regDP0_DP_VID_N",
    "DP_VID_M": "regDP0_DP_VID_M",
    "DP_SEC_CNTL": "regDP0_DP_SEC_CNTL",
    "DP_SEC_CNTL1": "regDP0_DP_SEC_CNTL1",
    "DP_MSE_RATE_CNTL": "regDP0_DP_MSE_RATE_CNTL",
    "DP_MSE_RATE_UPDATE": "regDP0_DP_MSE_RATE_UPDATE",
    "DP_MSA_TIMING_PARAM1": "regDP0_DP_MSA_TIMING_PARAM1",
    "DP_MSA_TIMING_PARAM2": "regDP0_DP_MSA_TIMING_PARAM2",
    "DP_MSA_TIMING_PARAM3": "regDP0_DP_MSA_TIMING_PARAM3",
    "DP_MSA_TIMING_PARAM4": "regDP0_DP_MSA_TIMING_PARAM4",
    "DP_DSC_CNTL": "regDP0_DP_DSC_CNTL",
    "DP_SEC_CNTL2": "regDP0_DP_SEC_CNTL2",
    "DP_DB_CNTL": "regDP0_DP_DB_CNTL",
    "DP_MSA_VBID_MISC": "regDP0_DP_MSA_VBID_MISC",
    "DP_SEC_TIMESTAMP": "regDP0_DP_SEC_TIMESTAMP",
    "DP_SEC_AUD_N": "regDP0_DP_SEC_AUD_N",
    "DP_LINK_CNTL": "regDP0_DP_LINK_CNTL",
    # ── DSC（核心几个，后续暂不依赖）──
    "DSC_TOP_CONTROL": "regDSC_TOP0_DSC_TOP_CONTROL",
    "DSCCIF_CONFIG0": "regDSCCIF0_DSCCIF_CONFIG0",
    "DSCCIF_CONFIG1": "regDSCCIF0_DSCCIF_CONFIG1",
    "DSCC_CONFIG0": "regDSCC0_DSCC_CONFIG0",
    # ── 中断（无 OTG0_INT_* 命名寄存器，按 irq_service_dcn314.c）──
    "OTG_GLOBAL_SYNC_STATUS": "regOTG0_OTG_GLOBAL_SYNC_STATUS",
    "DCSURF_SURFACE_FLIP_INTERRUPT": "regHUBPREQ0_DCSURF_SURFACE_FLIP_INTERRUPT",
    "HPD_INT_STATUS": "regHPD0_DC_HPD_INT_STATUS",
    "HPD_INT_CONTROL": "regHPD0_DC_HPD_INT_CONTROL",
    "HPD_CONTROL": "regHPD0_DC_HPD_CONTROL",
}

# 段基址类：yellow_carp_offset.h 的 DCN_BASE__INST0_SEGn（DCN314.hpp 的 DCN_SEG*_BASE）
SEG_ENTRIES = {
    "DCN_SEG0_BASE": "DCN_BASE__INST0_SEG0",
    "DCN_SEG1_BASE": "DCN_BASE__INST0_SEG1",
    "DCN_SEG2_BASE": "DCN_BASE__INST0_SEG2",
    "DCN_SEG3_BASE": "DCN_BASE__INST0_SEG3",
    "DCN_SEG4_BASE": "DCN_BASE__INST0_SEG4",
}

MASKS = {
    # DENTIST_DISPCLK_CNTL（补 CHG_MODE；WDIVIDER/RDIVIDER 既有）
    "DENTIST_DISPCLK_CHG_MODE_SHIFT": ("DENTIST_DISPCLK_CNTL", "DENTIST_DISPCLK_CHG_MODE", "SHIFT"),
    "DENTIST_DISPCLK_CHG_MODE_MASK": ("DENTIST_DISPCLK_CNTL", "DENTIST_DISPCLK_CHG_MODE", "MASK"),
    # OTG_PIXEL_RATE_DIV（OTG0..3 打包单寄存器）
    "OTG0_PIXEL_RATE_DIVK1_SHIFT": ("OTG_PIXEL_RATE_DIV", "OTG0_PIXEL_RATE_DIVK1", "SHIFT"),
    "OTG0_PIXEL_RATE_DIVK1_MASK": ("OTG_PIXEL_RATE_DIV", "OTG0_PIXEL_RATE_DIVK1", "MASK"),
    "OTG0_PIXEL_RATE_DIVK2_SHIFT": ("OTG_PIXEL_RATE_DIV", "OTG0_PIXEL_RATE_DIVK2", "SHIFT"),
    "OTG0_PIXEL_RATE_DIVK2_MASK": ("OTG_PIXEL_RATE_DIV", "OTG0_PIXEL_RATE_DIVK2", "MASK"),
    "OTG1_PIXEL_RATE_DIVK1_SHIFT": ("OTG_PIXEL_RATE_DIV", "OTG1_PIXEL_RATE_DIVK1", "SHIFT"),
    "OTG1_PIXEL_RATE_DIVK1_MASK": ("OTG_PIXEL_RATE_DIV", "OTG1_PIXEL_RATE_DIVK1", "MASK"),
    "OTG1_PIXEL_RATE_DIVK2_SHIFT": ("OTG_PIXEL_RATE_DIV", "OTG1_PIXEL_RATE_DIVK2", "SHIFT"),
    "OTG1_PIXEL_RATE_DIVK2_MASK": ("OTG_PIXEL_RATE_DIV", "OTG1_PIXEL_RATE_DIVK2", "MASK"),
    "OTG2_PIXEL_RATE_DIVK1_SHIFT": ("OTG_PIXEL_RATE_DIV", "OTG2_PIXEL_RATE_DIVK1", "SHIFT"),
    "OTG2_PIXEL_RATE_DIVK1_MASK": ("OTG_PIXEL_RATE_DIV", "OTG2_PIXEL_RATE_DIVK1", "MASK"),
    "OTG2_PIXEL_RATE_DIVK2_SHIFT": ("OTG_PIXEL_RATE_DIV", "OTG2_PIXEL_RATE_DIVK2", "SHIFT"),
    "OTG2_PIXEL_RATE_DIVK2_MASK": ("OTG_PIXEL_RATE_DIV", "OTG2_PIXEL_RATE_DIVK2", "MASK"),
    "OTG3_PIXEL_RATE_DIVK1_SHIFT": ("OTG_PIXEL_RATE_DIV", "OTG3_PIXEL_RATE_DIVK1", "SHIFT"),
    "OTG3_PIXEL_RATE_DIVK1_MASK": ("OTG_PIXEL_RATE_DIV", "OTG3_PIXEL_RATE_DIVK1", "MASK"),
    "OTG3_PIXEL_RATE_DIVK2_SHIFT": ("OTG_PIXEL_RATE_DIV", "OTG3_PIXEL_RATE_DIVK2", "SHIFT"),
    "OTG3_PIXEL_RATE_DIVK2_MASK": ("OTG_PIXEL_RATE_DIV", "OTG3_PIXEL_RATE_DIVK2", "MASK"),
    # DCCG_GATE_DISABLE_CNTL2（PHYxSYMCLK 门控）
    "PHYASYMCLK_GATE_DISABLE_SHIFT": ("DCCG_GATE_DISABLE_CNTL2", "PHYASYMCLK_GATE_DISABLE", "SHIFT"),
    "PHYASYMCLK_GATE_DISABLE_MASK": ("DCCG_GATE_DISABLE_CNTL2", "PHYASYMCLK_GATE_DISABLE", "MASK"),
    "PHYESYMCLK_GATE_DISABLE_SHIFT": ("DCCG_GATE_DISABLE_CNTL2", "PHYESYMCLK_GATE_DISABLE", "SHIFT"),
    "PHYESYMCLK_GATE_DISABLE_MASK": ("DCCG_GATE_DISABLE_CNTL2", "PHYESYMCLK_GATE_DISABLE", "MASK"),
    # DCCG_GATE_DISABLE_CNTL3（SYMCLK32_SE 门控）
    "SYMCLK32_SE0_GATE_DISABLE_SHIFT": ("DCCG_GATE_DISABLE_CNTL3", "SYMCLK32_SE0_GATE_DISABLE", "SHIFT"),
    "SYMCLK32_SE0_GATE_DISABLE_MASK": ("DCCG_GATE_DISABLE_CNTL3", "SYMCLK32_SE0_GATE_DISABLE", "MASK"),
    # DIG_FE_CNTL
    "DIG_SOURCE_SELECT_SHIFT": ("DIG0_DIG_FE_CNTL", "DIG_SOURCE_SELECT", "SHIFT"),
    "DIG_SOURCE_SELECT_MASK": ("DIG0_DIG_FE_CNTL", "DIG_SOURCE_SELECT", "MASK"),
    "DIG_INPUT_PIXEL_SELECT_SHIFT": ("DIG0_DIG_FE_CNTL", "DIG_INPUT_PIXEL_SELECT", "SHIFT"),
    "DIG_INPUT_PIXEL_SELECT_MASK": ("DIG0_DIG_FE_CNTL", "DIG_INPUT_PIXEL_SELECT", "MASK"),
    "DIG_SYMCLK_FE_ON_SHIFT": ("DIG0_DIG_FE_CNTL", "DIG_SYMCLK_FE_ON", "SHIFT"),
    "DIG_SYMCLK_FE_ON_MASK": ("DIG0_DIG_FE_CNTL", "DIG_SYMCLK_FE_ON", "MASK"),
    # DIG_BE_CNTL
    "DIG_FE_SOURCE_SELECT_SHIFT": ("DIG0_DIG_BE_CNTL", "DIG_FE_SOURCE_SELECT", "SHIFT"),
    "DIG_FE_SOURCE_SELECT_MASK": ("DIG0_DIG_BE_CNTL", "DIG_FE_SOURCE_SELECT", "MASK"),
    "DIG_MODE_SHIFT": ("DIG0_DIG_BE_CNTL", "DIG_MODE", "SHIFT"),
    "DIG_MODE_MASK": ("DIG0_DIG_BE_CNTL", "DIG_MODE", "MASK"),
    "DIG_HPD_SELECT_SHIFT": ("DIG0_DIG_BE_CNTL", "DIG_HPD_SELECT", "SHIFT"),
    "DIG_HPD_SELECT_MASK": ("DIG0_DIG_BE_CNTL", "DIG_HPD_SELECT", "MASK"),
    # DIG_BE_EN_CNTL
    "DIG_ENABLE_SHIFT": ("DIG0_DIG_BE_EN_CNTL", "DIG_ENABLE", "SHIFT"),
    "DIG_ENABLE_MASK": ("DIG0_DIG_BE_EN_CNTL", "DIG_ENABLE", "MASK"),
    "DIG_SYMCLK_BE_ON_SHIFT": ("DIG0_DIG_BE_EN_CNTL", "DIG_SYMCLK_BE_ON", "SHIFT"),
    "DIG_SYMCLK_BE_ON_MASK": ("DIG0_DIG_BE_EN_CNTL", "DIG_SYMCLK_BE_ON", "MASK"),
    # DIG_CLOCK_PATTERN
    "DIG_CLOCK_PATTERN_FIELD_SHIFT": ("DIG0_DIG_CLOCK_PATTERN", "DIG_CLOCK_PATTERN", "SHIFT"),
    "DIG_CLOCK_PATTERN_FIELD_MASK": ("DIG0_DIG_CLOCK_PATTERN", "DIG_CLOCK_PATTERN", "MASK"),
    # DIG_FIFO_CTRL0（dcn314 流编码器 DIG FIFO）
    "DIG_FIFO_ENABLE_SHIFT": ("DIG0_DIG_FIFO_CTRL0", "DIG_FIFO_ENABLE", "SHIFT"),
    "DIG_FIFO_ENABLE_MASK": ("DIG0_DIG_FIFO_CTRL0", "DIG_FIFO_ENABLE", "MASK"),
    "DIG_FIFO_RESET_SHIFT": ("DIG0_DIG_FIFO_CTRL0", "DIG_FIFO_RESET", "SHIFT"),
    "DIG_FIFO_RESET_MASK": ("DIG0_DIG_FIFO_CTRL0", "DIG_FIFO_RESET", "MASK"),
    "DIG_FIFO_READ_START_LEVEL_SHIFT": ("DIG0_DIG_FIFO_CTRL0", "DIG_FIFO_READ_START_LEVEL", "SHIFT"),
    "DIG_FIFO_READ_START_LEVEL_MASK": ("DIG0_DIG_FIFO_CTRL0", "DIG_FIFO_READ_START_LEVEL", "MASK"),
    "DIG_FIFO_RESET_DONE_SHIFT": ("DIG0_DIG_FIFO_CTRL0", "DIG_FIFO_RESET_DONE", "SHIFT"),
    "DIG_FIFO_RESET_DONE_MASK": ("DIG0_DIG_FIFO_CTRL0", "DIG_FIFO_RESET_DONE", "MASK"),
    # DP_VID_STREAM_CNTL
    "DP_VID_STREAM_ENABLE_SHIFT": ("DP0_DP_VID_STREAM_CNTL", "DP_VID_STREAM_ENABLE", "SHIFT"),
    "DP_VID_STREAM_ENABLE_MASK": ("DP0_DP_VID_STREAM_CNTL", "DP_VID_STREAM_ENABLE", "MASK"),
    "DP_VID_STREAM_DIS_DEFER_SHIFT": ("DP0_DP_VID_STREAM_CNTL", "DP_VID_STREAM_DIS_DEFER", "SHIFT"),
    "DP_VID_STREAM_DIS_DEFER_MASK": ("DP0_DP_VID_STREAM_CNTL", "DP_VID_STREAM_DIS_DEFER", "MASK"),
    "DP_VID_STREAM_STATUS_SHIFT": ("DP0_DP_VID_STREAM_CNTL", "DP_VID_STREAM_STATUS", "SHIFT"),
    "DP_VID_STREAM_STATUS_MASK": ("DP0_DP_VID_STREAM_CNTL", "DP_VID_STREAM_STATUS", "MASK"),
    # DP_STEER_FIFO
    "DP_STEER_FIFO_RESET_SHIFT": ("DP0_DP_STEER_FIFO", "DP_STEER_FIFO_RESET", "SHIFT"),
    "DP_STEER_FIFO_RESET_MASK": ("DP0_DP_STEER_FIFO", "DP_STEER_FIFO_RESET", "MASK"),
    # DP_PIXEL_FORMAT
    "DP_PIXEL_ENCODING_SHIFT": ("DP0_DP_PIXEL_FORMAT", "DP_PIXEL_ENCODING", "SHIFT"),
    "DP_PIXEL_ENCODING_MASK": ("DP0_DP_PIXEL_FORMAT", "DP_PIXEL_ENCODING", "MASK"),
    "DP_COMPONENT_DEPTH_SHIFT": ("DP0_DP_PIXEL_FORMAT", "DP_COMPONENT_DEPTH", "SHIFT"),
    "DP_COMPONENT_DEPTH_MASK": ("DP0_DP_PIXEL_FORMAT", "DP_COMPONENT_DEPTH", "MASK"),
    # DP_SEC_CNTL
    "DP_SEC_STREAM_ENABLE_SHIFT": ("DP0_DP_SEC_CNTL", "DP_SEC_STREAM_ENABLE", "SHIFT"),
    "DP_SEC_STREAM_ENABLE_MASK": ("DP0_DP_SEC_CNTL", "DP_SEC_STREAM_ENABLE", "MASK"),
    "DP_SEC_MPG_ENABLE_SHIFT": ("DP0_DP_SEC_CNTL", "DP_SEC_MPG_ENABLE", "SHIFT"),
    "DP_SEC_MPG_ENABLE_MASK": ("DP0_DP_SEC_CNTL", "DP_SEC_MPG_ENABLE", "MASK"),
    # DP_VID_TIMING
    "DP_VID_M_N_GEN_EN_SHIFT": ("DP0_DP_VID_TIMING", "DP_VID_M_N_GEN_EN", "SHIFT"),
    "DP_VID_M_N_GEN_EN_MASK": ("DP0_DP_VID_TIMING", "DP_VID_M_N_GEN_EN", "MASK"),
    # DP_VID_M/N
    "DP_VID_M_FIELD_SHIFT": ("DP0_DP_VID_M", "DP_VID_M", "SHIFT"),
    "DP_VID_M_FIELD_MASK": ("DP0_DP_VID_M", "DP_VID_M", "MASK"),
    "DP_VID_N_FIELD_SHIFT": ("DP0_DP_VID_N", "DP_VID_N", "SHIFT"),
    "DP_VID_N_FIELD_MASK": ("DP0_DP_VID_N", "DP_VID_N", "MASK"),
    # DP_LINK_CNTL（链路关闭路径）
    "DP_LINK_TRAINING_COMPLETE_SHIFT": ("DP0_DP_LINK_CNTL", "DP_LINK_TRAINING_COMPLETE", "SHIFT"),
    "DP_LINK_TRAINING_COMPLETE_MASK": ("DP0_DP_LINK_CNTL", "DP_LINK_TRAINING_COMPLETE", "MASK"),
    "DP_EMBEDDED_PANEL_MODE_SHIFT": ("DP0_DP_LINK_CNTL", "DP_EMBEDDED_PANEL_MODE", "SHIFT"),
    "DP_EMBEDDED_PANEL_MODE_MASK": ("DP0_DP_LINK_CNTL", "DP_EMBEDDED_PANEL_MODE", "MASK"),
    # DP_CONFIG
    "DP_UDI_LANES_SHIFT": ("DP0_DP_CONFIG", "DP_UDI_LANES", "SHIFT"),
    "DP_UDI_LANES_MASK": ("DP0_DP_CONFIG", "DP_UDI_LANES", "MASK"),
    # DP_SEC_TIMESTAMP
    "DP_SEC_TIMESTAMP_MODE_SHIFT": ("DP0_DP_SEC_TIMESTAMP", "DP_SEC_TIMESTAMP_MODE", "SHIFT"),
    "DP_SEC_TIMESTAMP_MODE_MASK": ("DP0_DP_SEC_TIMESTAMP", "DP_SEC_TIMESTAMP_MODE", "MASK"),
    # DP_DSC_CNTL
    "DP_DSC_MODE_SHIFT": ("DP0_DP_DSC_CNTL", "DP_DSC_MODE", "SHIFT"),
    "DP_DSC_MODE_MASK": ("DP0_DP_DSC_CNTL", "DP_DSC_MODE", "MASK"),
    # DSC_TOP_CONTROL
    "DSC_CLOCK_EN_SHIFT": ("DSC_TOP0_DSC_TOP_CONTROL", "DSC_CLOCK_EN", "SHIFT"),
    "DSC_CLOCK_EN_MASK": ("DSC_TOP0_DSC_TOP_CONTROL", "DSC_CLOCK_EN", "MASK"),
    # 中断：OTG 全局同步状态（VBLANK/VUPDATE 使能与清除）
    "OTG_VSTARTUP_INT_EN_SHIFT": ("OTG0_OTG_GLOBAL_SYNC_STATUS", "VSTARTUP_INT_EN", "SHIFT"),
    "OTG_VSTARTUP_INT_EN_MASK": ("OTG0_OTG_GLOBAL_SYNC_STATUS", "VSTARTUP_INT_EN", "MASK"),
    "OTG_VSTARTUP_EVENT_CLEAR_SHIFT": ("OTG0_OTG_GLOBAL_SYNC_STATUS", "VSTARTUP_EVENT_CLEAR", "SHIFT"),
    "OTG_VSTARTUP_EVENT_CLEAR_MASK": ("OTG0_OTG_GLOBAL_SYNC_STATUS", "VSTARTUP_EVENT_CLEAR", "MASK"),
    "OTG_VUPDATE_NO_LOCK_INT_EN_SHIFT": ("OTG0_OTG_GLOBAL_SYNC_STATUS", "VUPDATE_NO_LOCK_INT_EN", "SHIFT"),
    "OTG_VUPDATE_NO_LOCK_INT_EN_MASK": ("OTG0_OTG_GLOBAL_SYNC_STATUS", "VUPDATE_NO_LOCK_INT_EN", "MASK"),
    "OTG_VUPDATE_NO_LOCK_EVENT_CLEAR_SHIFT": ("OTG0_OTG_GLOBAL_SYNC_STATUS", "VUPDATE_NO_LOCK_EVENT_CLEAR", "SHIFT"),
    "OTG_VUPDATE_NO_LOCK_EVENT_CLEAR_MASK": ("OTG0_OTG_GLOBAL_SYNC_STATUS", "VUPDATE_NO_LOCK_EVENT_CLEAR", "MASK"),
    # 中断：翻页完成（PFLIP）
    "SURFACE_FLIP_INT_MASK_SHIFT": ("HUBPREQ0_DCSURF_SURFACE_FLIP_INTERRUPT", "SURFACE_FLIP_INT_MASK", "SHIFT"),
    "SURFACE_FLIP_INT_MASK_MASK": ("HUBPREQ0_DCSURF_SURFACE_FLIP_INTERRUPT", "SURFACE_FLIP_INT_MASK", "MASK"),
    "SURFACE_FLIP_CLEAR_SHIFT": ("HUBPREQ0_DCSURF_SURFACE_FLIP_INTERRUPT", "SURFACE_FLIP_CLEAR", "SHIFT"),
    "SURFACE_FLIP_CLEAR_MASK": ("HUBPREQ0_DCSURF_SURFACE_FLIP_INTERRUPT", "SURFACE_FLIP_CLEAR", "MASK"),
    # 中断：HPD（热插拔状态/屏蔽）
    "HPD_INT_EN_SHIFT": ("HPD0_DC_HPD_INT_CONTROL", "DC_HPD_INT_EN", "SHIFT"),
    "HPD_INT_EN_MASK": ("HPD0_DC_HPD_INT_CONTROL", "DC_HPD_INT_EN", "MASK"),
    "HPD_INT_ACK_SHIFT": ("HPD0_DC_HPD_INT_CONTROL", "DC_HPD_INT_ACK", "SHIFT"),
    "HPD_INT_ACK_MASK": ("HPD0_DC_HPD_INT_CONTROL", "DC_HPD_INT_ACK", "MASK"),
    "HPD_INT_STATUS_FIELD_SHIFT": ("HPD0_DC_HPD_INT_STATUS", "DC_HPD_INT_STATUS", "SHIFT"),
    "HPD_INT_STATUS_FIELD_MASK": ("HPD0_DC_HPD_INT_STATUS", "DC_HPD_INT_STATUS", "MASK"),
    # DP_SEC_CNTL1（GSP0 行号）
    "DP_SEC_GSP0_LINE_NUM_SHIFT": ("DP0_DP_SEC_CNTL1", "DP_SEC_GSP0_LINE_NUM", "SHIFT"),
    "DP_SEC_GSP0_LINE_NUM_MASK": ("DP0_DP_SEC_CNTL1", "DP_SEC_GSP0_LINE_NUM", "MASK"),
    # DP_MSA_TIMING_PARAM1..4（MSA 时序四件套关键字段）
    "DP_MSA_VTOTAL_SHIFT": ("DP0_DP_MSA_TIMING_PARAM1", "DP_MSA_VTOTAL", "SHIFT"),
    "DP_MSA_VTOTAL_MASK": ("DP0_DP_MSA_TIMING_PARAM1", "DP_MSA_VTOTAL", "MASK"),
    "DP_MSA_HTOTAL_SHIFT": ("DP0_DP_MSA_TIMING_PARAM1", "DP_MSA_HTOTAL", "SHIFT"),
    "DP_MSA_HTOTAL_MASK": ("DP0_DP_MSA_TIMING_PARAM1", "DP_MSA_HTOTAL", "MASK"),
    "DP_MSA_VSTART_SHIFT": ("DP0_DP_MSA_TIMING_PARAM2", "DP_MSA_VSTART", "SHIFT"),
    "DP_MSA_VSTART_MASK": ("DP0_DP_MSA_TIMING_PARAM2", "DP_MSA_VSTART", "MASK"),
    "DP_MSA_HSTART_SHIFT": ("DP0_DP_MSA_TIMING_PARAM2", "DP_MSA_HSTART", "SHIFT"),
    "DP_MSA_HSTART_MASK": ("DP0_DP_MSA_TIMING_PARAM2", "DP_MSA_HSTART", "MASK"),
    "DP_MSA_VSYNCWIDTH_SHIFT": ("DP0_DP_MSA_TIMING_PARAM3", "DP_MSA_VSYNCWIDTH", "SHIFT"),
    "DP_MSA_VSYNCWIDTH_MASK": ("DP0_DP_MSA_TIMING_PARAM3", "DP_MSA_VSYNCWIDTH", "MASK"),
    "DP_MSA_HSYNCWIDTH_SHIFT": ("DP0_DP_MSA_TIMING_PARAM3", "DP_MSA_HSYNCWIDTH", "SHIFT"),
    "DP_MSA_HSYNCWIDTH_MASK": ("DP0_DP_MSA_TIMING_PARAM3", "DP_MSA_HSYNCWIDTH", "MASK"),
    "DP_MSA_VHEIGHT_SHIFT": ("DP0_DP_MSA_TIMING_PARAM4", "DP_MSA_VHEIGHT", "SHIFT"),
    "DP_MSA_VHEIGHT_MASK": ("DP0_DP_MSA_TIMING_PARAM4", "DP_MSA_VHEIGHT", "MASK"),
    "DP_MSA_HWIDTH_SHIFT": ("DP0_DP_MSA_TIMING_PARAM4", "DP_MSA_HWIDTH", "SHIFT"),
    "DP_MSA_HWIDTH_MASK": ("DP0_DP_MSA_TIMING_PARAM4", "DP_MSA_HWIDTH", "MASK"),
    # DP_DB_CNTL（双重缓冲）
    "DP_DB_LOCK_SHIFT": ("DP0_DP_DB_CNTL", "DP_DB_LOCK", "SHIFT"),
    "DP_DB_LOCK_MASK": ("DP0_DP_DB_CNTL", "DP_DB_LOCK", "MASK"),
    "DP_DB_DISABLE_SHIFT": ("DP0_DP_DB_CNTL", "DP_DB_DISABLE", "SHIFT"),
    "DP_DB_DISABLE_MASK": ("DP0_DP_DB_CNTL", "DP_DB_DISABLE", "MASK"),
    # DP_MSE（MST 多流；保留给后续 MST 路径）
    "DP_MSE_RATE_Y_SHIFT": ("DP0_DP_MSE_RATE_CNTL", "DP_MSE_RATE_Y", "SHIFT"),
    "DP_MSE_RATE_Y_MASK": ("DP0_DP_MSE_RATE_CNTL", "DP_MSE_RATE_Y", "MASK"),
    "DP_MSE_RATE_X_SHIFT": ("DP0_DP_MSE_RATE_CNTL", "DP_MSE_RATE_X", "SHIFT"),
    "DP_MSE_RATE_X_MASK": ("DP0_DP_MSE_RATE_CNTL", "DP_MSE_RATE_X", "MASK"),
    "DP_MSE_RATE_UPDATE_PENDING_SHIFT": ("DP0_DP_MSE_RATE_UPDATE", "DP_MSE_RATE_UPDATE_PENDING", "SHIFT"),
    "DP_MSE_RATE_UPDATE_PENDING_MASK": ("DP0_DP_MSE_RATE_UPDATE", "DP_MSE_RATE_UPDATE_PENDING", "MASK"),
    # DP_MSA_MISC / DP_MSA_VBID_MISC（MISC1/VBID 覆写）
    "DP_MSA_MISC1_SHIFT": ("DP0_DP_MSA_MISC", "DP_MSA_MISC1", "SHIFT"),
    "DP_MSA_MISC1_MASK": ("DP0_DP_MSA_MISC", "DP_MSA_MISC1", "MASK"),
    # DIG AFMT（音频时钟；AFMT_CNTL 既有寄存器的位域）
    "AFMT_AUDIO_CLOCK_EN_SHIFT": ("DIG0_AFMT_CNTL", "AFMT_AUDIO_CLOCK_EN", "SHIFT"),
    "AFMT_AUDIO_CLOCK_EN_MASK": ("DIG0_AFMT_CNTL", "AFMT_AUDIO_CLOCK_EN", "MASK"),
    # HPD_CONTROL（HPD 使能）
    "DC_HPD_EN_SHIFT": ("HPD0_DC_HPD_CONTROL", "DC_HPD_EN", "SHIFT"),
    "DC_HPD_EN_MASK": ("HPD0_DC_HPD_CONTROL", "DC_HPD_EN", "MASK"),
    # DC_MEM_GLOBAL_PWR_REQ_CNTL（内存低功耗门控）
    "DC_MEM_GLOBAL_PWR_REQ_DIS_SHIFT": ("DC_MEM_GLOBAL_PWR_REQ_CNTL", "DC_MEM_GLOBAL_PWR_REQ_DIS", "SHIFT"),
    "DC_MEM_GLOBAL_PWR_REQ_DIS_MASK": ("DC_MEM_GLOBAL_PWR_REQ_CNTL", "DC_MEM_GLOBAL_PWR_REQ_DIS", "MASK"),
    # MICROSECOND_TIME_BASE_DIV（微秒基准，REG_WAIT 延时依赖）
    "MICROSECOND_TIME_BASE_DIV_SHIFT": ("MICROSECOND_TIME_BASE_DIV", "MICROSECOND_TIME_BASE_DIV", "SHIFT"),
    "MICROSECOND_TIME_BASE_DIV_MASK": ("MICROSECOND_TIME_BASE_DIV", "MICROSECOND_TIME_BASE_DIV", "MASK"),
    # DP_SEC_TIMESTAMP 已有 SHIFT/MASK；DP_VID_TIMING 双缓冲
    "DP_VID_M_N_DOUBLE_BUFFER_MODE_SHIFT": ("DP0_DP_VID_TIMING", "DP_VID_M_N_DOUBLE_BUFFER_MODE", "SHIFT"),
    "DP_VID_M_N_DOUBLE_BUFFER_MODE_MASK": ("DP0_DP_VID_TIMING", "DP_VID_M_N_DOUBLE_BUFFER_MODE", "MASK"),
    # DTBCLK_P_CNTL（dtbclk_p 源选择/使能，dccg314_set_dtbclk_p_src）
    "DTBCLK_P0_SRC_SEL_SHIFT": ("DTBCLK_P_CNTL", "DTBCLK_P0_SRC_SEL", "SHIFT"),
    "DTBCLK_P0_SRC_SEL_MASK": ("DTBCLK_P_CNTL", "DTBCLK_P0_SRC_SEL", "MASK"),
    "DTBCLK_P0_EN_SHIFT": ("DTBCLK_P_CNTL", "DTBCLK_P0_EN", "SHIFT"),
    "DTBCLK_P0_EN_MASK": ("DTBCLK_P_CNTL", "DTBCLK_P0_EN", "MASK"),
    # OTG_PIXEL_RATE_CNTL（像素率时钟源/使能，既有寄存器的完整位域）
    "OTG0_PIXEL_RATE_SOURCE_SHIFT": ("OTG0_PIXEL_RATE_CNTL", "OTG0_PIXEL_RATE_SOURCE", "SHIFT"),
    "OTG0_PIXEL_RATE_SOURCE_MASK": ("OTG0_PIXEL_RATE_CNTL", "OTG0_PIXEL_RATE_SOURCE", "MASK"),
    "DP_DTO0_ENABLE_SHIFT": ("OTG0_PIXEL_RATE_CNTL", "DP_DTO0_ENABLE", "SHIFT"),
    "DP_DTO0_ENABLE_MASK": ("OTG0_PIXEL_RATE_CNTL", "DP_DTO0_ENABLE", "MASK"),
    "PIPE0_DTO_SRC_SEL_SHIFT": ("OTG0_PIXEL_RATE_CNTL", "PIPE0_DTO_SRC_SEL", "SHIFT"),
    "PIPE0_DTO_SRC_SEL_MASK": ("OTG0_PIXEL_RATE_CNTL", "PIPE0_DTO_SRC_SEL", "MASK"),
    # DPPCLK_DTO_CTRL（DPP 时钟 DTO，dccg314_dpp_root_clock_control）
    "DPPCLK0_DTO_ENABLE_SHIFT": ("DPPCLK_DTO_CTRL", "DPPCLK0_DTO_ENABLE", "SHIFT"),
    "DPPCLK0_DTO_ENABLE_MASK": ("DPPCLK_DTO_CTRL", "DPPCLK0_DTO_ENABLE", "MASK"),
    "DPPCLK0_DTO_DB_EN_SHIFT": ("DPPCLK_DTO_CTRL", "DPPCLK0_DTO_DB_EN", "SHIFT"),
    "DPPCLK0_DTO_DB_EN_MASK": ("DPPCLK_DTO_CTRL", "DPPCLK0_DTO_DB_EN", "MASK"),
    "DPPCLK0_DTO_PHASE_SHIFT": ("DPPCLK0_DTO_PARAM", "DPPCLK0_DTO_PHASE", "SHIFT"),
    "DPPCLK0_DTO_PHASE_MASK": ("DPPCLK0_DTO_PARAM", "DPPCLK0_DTO_PHASE", "MASK"),
    "DPPCLK0_DTO_MODULO_SHIFT": ("DPPCLK0_DTO_PARAM", "DPPCLK0_DTO_MODULO", "SHIFT"),
    "DPPCLK0_DTO_MODULO_MASK": ("DPPCLK0_DTO_PARAM", "DPPCLK0_DTO_MODULO", "MASK"),
    # ── 既有位域抽样回归（update_odm/resync_fifo 用）──
    "OPTC_NUM_OF_INPUT_SEGMENT_SHIFT": ("ODM0_OPTC_DATA_SOURCE_SELECT", "OPTC_NUM_OF_INPUT_SEGMENT", "SHIFT"),
    "OPTC_NUM_OF_INPUT_SEGMENT_MASK": ("ODM0_OPTC_DATA_SOURCE_SELECT", "OPTC_NUM_OF_INPUT_SEGMENT", "MASK"),
    "OPTC_WIDTH_CONTROL_OPTC_DSC_SLICE_WIDTH_SHIFT": ("ODM0_OPTC_WIDTH_CONTROL", "OPTC_DSC_SLICE_WIDTH", "SHIFT"),
    "OPTC_WIDTH_CONTROL_OPTC_DSC_SLICE_WIDTH_MASK": ("ODM0_OPTC_WIDTH_CONTROL", "OPTC_DSC_SLICE_WIDTH", "MASK"),
    "OPTC_NUM_OF_OUTPUT_SEGMENT_SHIFT": ("ODM0_OPTC_DATA_SOURCE_SELECT", "OPTC_NUM_OF_OUTPUT_SEGMENT", "SHIFT"),
    "OPTC_NUM_OF_OUTPUT_SEGMENT_MASK": ("ODM0_OPTC_DATA_SOURCE_SELECT", "OPTC_NUM_OF_OUTPUT_SEGMENT", "MASK"),
    "OPTC_SEG0_SRC_SEL_SHIFT": ("ODM0_OPTC_DATA_SOURCE_SELECT", "OPTC_SEG0_SRC_SEL", "SHIFT"),
    "OPTC_SEG0_SRC_SEL_MASK": ("ODM0_OPTC_DATA_SOURCE_SELECT", "OPTC_SEG0_SRC_SEL", "MASK"),
    "OPTC_SEG1_SRC_SEL_SHIFT": ("ODM0_OPTC_DATA_SOURCE_SELECT", "OPTC_SEG1_SRC_SEL", "SHIFT"),
    "OPTC_SEG1_SRC_SEL_MASK": ("ODM0_OPTC_DATA_SOURCE_SELECT", "OPTC_SEG1_SRC_SEL", "MASK"),
    "OPTC_SEG2_SRC_SEL_SHIFT": ("ODM0_OPTC_DATA_SOURCE_SELECT", "OPTC_SEG2_SRC_SEL", "SHIFT"),
    "OPTC_SEG2_SRC_SEL_MASK": ("ODM0_OPTC_DATA_SOURCE_SELECT", "OPTC_SEG2_SRC_SEL", "MASK"),
    "OPTC_SEG3_SRC_SEL_SHIFT": ("ODM0_OPTC_DATA_SOURCE_SELECT", "OPTC_SEG3_SRC_SEL", "SHIFT"),
    "OPTC_SEG3_SRC_SEL_MASK": ("ODM0_OPTC_DATA_SOURCE_SELECT", "OPTC_SEG3_SRC_SEL", "MASK"),
    "OPTC_MEMORY_CONFIG_OPTC_MEM_SEL_SHIFT": ("ODM0_OPTC_MEMORY_CONFIG", "OPTC_MEM_SEL", "SHIFT"),
    "OPTC_MEMORY_CONFIG_OPTC_MEM_SEL_MASK": ("ODM0_OPTC_MEMORY_CONFIG", "OPTC_MEM_SEL", "MASK"),
    "OPTC_MEMORY_CONFIG_OPTC_MEM_SEL_STATUS_SHIFT": ("ODM0_OPTC_MEMORY_CONFIG", "OPTC_MEM_SEL_STATUS", "SHIFT"),
    "OPTC_MEMORY_CONFIG_OPTC_MEM_SEL_STATUS_MASK": ("ODM0_OPTC_MEMORY_CONFIG", "OPTC_MEM_SEL_STATUS", "MASK"),
    "OPTC_WIDTH_CONTROL_OPTC_SEGMENT_WIDTH_SHIFT": ("ODM0_OPTC_WIDTH_CONTROL", "OPTC_SEGMENT_WIDTH", "SHIFT"),
    "OTG_H_TIMING_DIV_MODE_SHIFT": ("OTG0_OTG_H_TIMING_CNTL", "OTG_H_TIMING_DIV_MODE", "SHIFT"),
    "OTG_H_TIMING_DIV_MODE_MASK": ("OTG0_OTG_H_TIMING_CNTL", "OTG_H_TIMING_DIV_MODE", "MASK"),
    "OTG_H_TIMING_DIV_MODE_MANUAL_SHIFT": ("OTG0_OTG_H_TIMING_CNTL", "OTG_H_TIMING_DIV_MODE_MANUAL", "SHIFT"),
    "OTG_H_TIMING_DIV_MODE_MANUAL_MASK": ("OTG0_OTG_H_TIMING_CNTL", "OTG_H_TIMING_DIV_MODE_MANUAL", "MASK"),
    "OTG_H_TIMING_DIV_MODE_CURR_SHIFT": ("OTG0_OTG_H_TIMING_CNTL", "OTG_H_TIMING_DIV_MODE_CURR", "SHIFT"),
    "OTG_H_TIMING_DIV_MODE_CURR_MASK": ("OTG0_OTG_H_TIMING_CNTL", "OTG_H_TIMING_DIV_MODE_CURR", "MASK"),
    "DENTIST_DISPCLK_WDIVIDER_SHIFT": ("DENTIST_DISPCLK_CNTL", "DENTIST_DISPCLK_WDIVIDER", "SHIFT"),
    "DENTIST_DISPCLK_WDIVIDER_MASK": ("DENTIST_DISPCLK_CNTL", "DENTIST_DISPCLK_WDIVIDER", "MASK"),
    "DENTIST_DISPCLK_RDIVIDER_SHIFT": ("DENTIST_DISPCLK_CNTL", "DENTIST_DISPCLK_RDIVIDER", "SHIFT"),
    "DENTIST_DISPCLK_RDIVIDER_MASK": ("DENTIST_DISPCLK_CNTL", "DENTIST_DISPCLK_RDIVIDER", "MASK"),
}


def main() -> None:
    for name, macro in ENTRIES.items():
        print(f"{name}={offval(macro):X}")
    for name, macro in SEG_ENTRIES.items():
        print(f"{name}={segval(macro):X}")
    for name, (block, field, kind) in MASKS.items():
        v = shiftval(block, field) if kind == "SHIFT" else maskval(block, field)
        print(f"{name}={v:X}")


if __name__ == "__main__":
    main()
